apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lqw1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uylh-tenant/rhtap-demo-app/hacbs-test-project-lqw1@sha256:678ff851ff10f375fde4134ecb3c52beeee936f23fa73769822b60cafccb2b9d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
